// Curated Nigerian trivia bank — Milestone 1 launch set.
//
// Selection criteria: evergreen facts only. Volatile facts (chart positions,
// recent transfers, current rankings, populations) are intentionally excluded
// to keep the bank accurate over time. M3 expands this to ~200 with explicit
// source URLs verified per question.

import type { TriviaQuestion } from '../../contracts/index.js';

export const TRIVIA_BANK: TriviaQuestion[] = [
  // ── History (10) ──────────────────────────────────────────────────────
  {
    id: 'h-001',
    category: 'history',
    difficulty: 'easy',
    question: 'In what year did Nigeria gain independence from Britain?',
    options: ['1957', '1960', '1963', '1966'],
    correctIndex: 1,
    source: 'https://en.wikipedia.org/wiki/Nigeria',
  },
  {
    id: 'h-002',
    category: 'history',
    difficulty: 'easy',
    question: "Who was Nigeria's first President?",
    options: ['Nnamdi Azikiwe', 'Tafawa Balewa', 'Yakubu Gowon', 'Obafemi Awolowo'],
    correctIndex: 0,
    source: 'https://en.wikipedia.org/wiki/Nnamdi_Azikiwe',
  },
  {
    id: 'h-003',
    category: 'history',
    difficulty: 'easy',
    question: "Who was Nigeria's first Prime Minister?",
    options: ['Ahmadu Bello', 'Tafawa Balewa', 'Obafemi Awolowo', 'Murtala Muhammed'],
    correctIndex: 1,
    source: 'https://en.wikipedia.org/wiki/Abubakar_Tafawa_Balewa',
  },
  {
    id: 'h-004',
    category: 'history',
    difficulty: 'medium',
    question: 'The Nigerian Civil War (Biafran War) ended in what year?',
    options: ['1967', '1969', '1970', '1972'],
    correctIndex: 2,
    source: 'https://en.wikipedia.org/wiki/Nigerian_Civil_War',
  },
  {
    id: 'h-005',
    category: 'history',
    difficulty: 'medium',
    question: 'In what year was the Federal Capital moved from Lagos to Abuja?',
    options: ['1976', '1985', '1991', '1999'],
    correctIndex: 2,
    source: 'https://en.wikipedia.org/wiki/Abuja',
  },
  {
    id: 'h-006',
    category: 'history',
    difficulty: 'medium',
    question: 'The ancient Nok civilization is best known for what kind of artifacts?',
    options: ['Bronze masks', 'Terracotta sculptures', 'Gold jewelry', 'Stone tablets'],
    correctIndex: 1,
    source: 'https://en.wikipedia.org/wiki/Nok_culture',
  },
  {
    id: 'h-007',
    category: 'history',
    difficulty: 'medium',
    question: 'Which empire, centred in present-day northern Nigeria, was founded by Usman dan Fodio?',
    options: ['Kanem-Bornu', 'Sokoto Caliphate', 'Songhai', 'Oyo'],
    correctIndex: 1,
    source: 'https://en.wikipedia.org/wiki/Sokoto_Caliphate',
  },
  {
    id: 'h-008',
    category: 'history',
    difficulty: 'hard',
    question: 'The Benin Bronzes were largely looted by British forces during which year?',
    options: ['1885', '1897', '1903', '1914'],
    correctIndex: 1,
    source: 'https://en.wikipedia.org/wiki/Benin_Bronzes',
  },
  {
    id: 'h-009',
    category: 'history',
    difficulty: 'medium',
    question: 'Nigeria became a Federal Republic in what year?',
    options: ['1960', '1963', '1979', '1999'],
    correctIndex: 1,
    source: 'https://en.wikipedia.org/wiki/History_of_Nigeria',
  },
  {
    id: 'h-010',
    category: 'history',
    difficulty: 'hard',
    question: 'Which Nigerian Head of State was assassinated in 1976?',
    options: ['Yakubu Gowon', 'Murtala Muhammed', 'Olusegun Obasanjo', 'Sani Abacha'],
    correctIndex: 1,
    source: 'https://en.wikipedia.org/wiki/Murtala_Mohammed',
  },

  // ── Geography (10) ────────────────────────────────────────────────────
  {
    id: 'g-001',
    category: 'geography',
    difficulty: 'easy',
    question: 'What is the capital of Nigeria?',
    options: ['Lagos', 'Abuja', 'Kano', 'Ibadan'],
    correctIndex: 1,
  },
  {
    id: 'g-002',
    category: 'geography',
    difficulty: 'easy',
    question: 'How many states does Nigeria have (excluding the FCT)?',
    options: ['30', '36', '37', '40'],
    correctIndex: 1,
    source: 'https://en.wikipedia.org/wiki/States_of_Nigeria',
  },
  {
    id: 'g-003',
    category: 'geography',
    difficulty: 'easy',
    question: 'The longest river in Nigeria is the…',
    options: ['Benue', 'Niger', 'Kaduna', 'Cross'],
    correctIndex: 1,
    source: 'https://en.wikipedia.org/wiki/Niger_River',
  },
  {
    id: 'g-004',
    category: 'geography',
    difficulty: 'easy',
    question: 'Which Nigerian city is widely called the “Coal City”?',
    options: ['Jos', 'Enugu', 'Kano', 'Port Harcourt'],
    correctIndex: 1,
    source: 'https://en.wikipedia.org/wiki/Enugu',
  },
  {
    id: 'g-005',
    category: 'geography',
    difficulty: 'medium',
    question: 'Zuma Rock is located near which Nigerian city?',
    options: ['Jos', 'Abuja', 'Kaduna', 'Minna'],
    correctIndex: 1,
    source: 'https://en.wikipedia.org/wiki/Zuma_Rock',
  },
  {
    id: 'g-006',
    category: 'geography',
    difficulty: 'medium',
    question: 'Olumo Rock, a famous tourist site, is located in which state?',
    options: ['Oyo', 'Ogun', 'Osun', 'Ondo'],
    correctIndex: 1,
    source: 'https://en.wikipedia.org/wiki/Olumo_Rock',
  },
  {
    id: 'g-007',
    category: 'geography',
    difficulty: 'medium',
    question: 'Which country does NOT share a land border with Nigeria?',
    options: ['Benin', 'Chad', 'Ghana', 'Cameroon'],
    correctIndex: 2,
    source: 'https://en.wikipedia.org/wiki/Geography_of_Nigeria',
  },
  {
    id: 'g-008',
    category: 'geography',
    difficulty: 'medium',
    question: 'The Niger and Benue rivers meet at which town?',
    options: ['Lokoja', 'Onitsha', 'Yola', 'Makurdi'],
    correctIndex: 0,
    source: 'https://en.wikipedia.org/wiki/Lokoja',
  },
  {
    id: 'g-009',
    category: 'geography',
    difficulty: 'hard',
    question: "Which is Nigeria's highest mountain?",
    options: ['Shere Hills', 'Chappal Waddi', 'Idanre Hills', 'Obudu Plateau'],
    correctIndex: 1,
    source: 'https://en.wikipedia.org/wiki/Chappal_Waddi',
  },
  {
    id: 'g-010',
    category: 'geography',
    difficulty: 'easy',
    question: 'Which Nigerian city was the federal capital before Abuja?',
    options: ['Ibadan', 'Lagos', 'Kaduna', 'Port Harcourt'],
    correctIndex: 1,
    source: 'https://en.wikipedia.org/wiki/Lagos',
  },

  // ── Culture & Language (10) ──────────────────────────────────────────
  {
    id: 'c-001',
    category: 'culture',
    difficulty: 'easy',
    question: 'Which are the three largest ethnic groups in Nigeria?',
    options: ['Hausa, Yoruba, Igbo', 'Edo, Tiv, Ijaw', 'Fulani, Kanuri, Igala', 'Efik, Ibibio, Nupe'],
    correctIndex: 0,
    source: 'https://en.wikipedia.org/wiki/Demographics_of_Nigeria',
  },
  {
    id: 'c-002',
    category: 'culture',
    difficulty: 'medium',
    question: 'The Gelede masquerade is a celebrated tradition of which ethnic group?',
    options: ['Igbo', 'Yoruba', 'Hausa', 'Edo'],
    correctIndex: 1,
    source: 'https://en.wikipedia.org/wiki/Gelede',
  },
  {
    id: 'c-003',
    category: 'culture',
    difficulty: 'medium',
    question: 'The traditional Igbo new yam festival is called…',
    options: ['Eyo', 'Iri Ji', 'Argungu', 'Osun-Osogbo'],
    correctIndex: 1,
    source: 'https://en.wikipedia.org/wiki/Iri_Ji',
  },
  {
    id: 'c-004',
    category: 'culture',
    difficulty: 'medium',
    question: 'The Argungu Fishing Festival is held in which state?',
    options: ['Sokoto', 'Kebbi', 'Zamfara', 'Niger'],
    correctIndex: 1,
    source: 'https://en.wikipedia.org/wiki/Argungu_Fishing_Festival',
  },
  {
    id: 'c-005',
    category: 'language',
    difficulty: 'easy',
    question: "What is Nigeria's official language?",
    options: ['Hausa', 'English', 'Yoruba', 'Igbo'],
    correctIndex: 1,
  },
  {
    id: 'c-006',
    category: 'language',
    difficulty: 'medium',
    question: 'Approximately how many languages are spoken in Nigeria?',
    options: ['Around 50', 'Around 100', 'Around 250', 'More than 500'],
    correctIndex: 3,
    source: 'https://en.wikipedia.org/wiki/Languages_of_Nigeria',
  },
  {
    id: 'c-007',
    category: 'language',
    difficulty: 'easy',
    question: 'In Nigerian Pidgin, what does “How far?” usually mean?',
    options: ['What distance?', "How's it going?", 'Where are you?', 'How much?'],
    correctIndex: 1,
  },
  {
    id: 'c-008',
    category: 'culture',
    difficulty: 'easy',
    question: '“Naija” is a popular informal name for…',
    options: ['Lagos', 'Nigeria', 'A type of music', 'A traditional dance'],
    correctIndex: 1,
  },
  {
    id: 'c-009',
    category: 'culture',
    difficulty: 'medium',
    question: 'Which Nigerian sacred grove is a UNESCO World Heritage Site?',
    options: ['Osun-Osogbo', 'Sukur', 'Idanre', 'Gashaka-Gumti'],
    correctIndex: 0,
    source: 'https://whc.unesco.org/en/list/1118/',
  },
  {
    id: 'c-010',
    category: 'culture',
    difficulty: 'hard',
    question: 'The Eyo Festival, with masqueraders in white robes, is associated with which city?',
    options: ['Ibadan', 'Lagos (Isale Eko)', 'Benin City', 'Calabar'],
    correctIndex: 1,
    source: 'https://en.wikipedia.org/wiki/Eyo_festival',
  },

  // ── Music (10) ────────────────────────────────────────────────────────
  {
    id: 'm-001',
    category: 'music',
    difficulty: 'easy',
    question: 'Which Nigerian musician is widely credited as the pioneer of Afrobeat?',
    options: ['King Sunny Adé', 'Fela Kuti', 'Ebenezer Obey', 'Sir Shina Peters'],
    correctIndex: 1,
    source: 'https://en.wikipedia.org/wiki/Fela_Kuti',
  },
  {
    id: 'm-002',
    category: 'music',
    difficulty: 'medium',
    question: 'Which genre is King Sunny Adé most associated with?',
    options: ['Highlife', 'Juju', 'Fuji', 'Apala'],
    correctIndex: 1,
    source: 'https://en.wikipedia.org/wiki/King_Sunny_Ad%C3%A9',
  },
  {
    id: 'm-003',
    category: 'music',
    difficulty: 'medium',
    question: 'Sikiru Ayinde Barrister is regarded as a foundational figure of which genre?',
    options: ['Juju', 'Fuji', 'Highlife', 'Apala'],
    correctIndex: 1,
    source: 'https://en.wikipedia.org/wiki/Sikiru_Ayinde_Barrister',
  },
  {
    id: 'm-004',
    category: 'music',
    difficulty: 'easy',
    question: 'Burna Boy won his first Grammy in which category?',
    options: ['Best New Artist', 'Best Global Music Album', 'Best R&B Album', 'Album of the Year'],
    correctIndex: 1,
    source: 'https://en.wikipedia.org/wiki/Burna_Boy',
  },
  {
    id: 'm-005',
    category: 'music',
    difficulty: 'medium',
    question: 'The 1980 album “Juju Music” brought international fame to which artist?',
    options: ['Ebenezer Obey', 'King Sunny Adé', 'Fela Kuti', 'Tunde Nightingale'],
    correctIndex: 1,
    source: 'https://en.wikipedia.org/wiki/Juju_Music',
  },
  {
    id: 'm-006',
    category: 'music',
    difficulty: 'medium',
    question: 'Which legendary highlife band was led by Victor Olaiya?',
    options: ['Cool Cats', 'All Stars', 'Rocafil Jazz', 'Oriental Brothers'],
    correctIndex: 1,
    source: 'https://en.wikipedia.org/wiki/Victor_Olaiya',
  },
  {
    id: 'm-007',
    category: 'music',
    difficulty: 'easy',
    question: 'Which Nigerian artist released the global hit song “Essence” featuring Tems?',
    options: ['Davido', 'Wizkid', 'Burna Boy', 'Rema'],
    correctIndex: 1,
    source: 'https://en.wikipedia.org/wiki/Essence_(Wizkid_song)',
  },
  {
    id: 'm-008',
    category: 'music',
    difficulty: 'hard',
    question: 'Fela Kuti famously named his Lagos compound and commune…',
    options: ['Afrika Shrine', 'Kalakuta Republic', 'Surulere House', 'Egbe Omo Oduduwa'],
    correctIndex: 1,
    source: 'https://en.wikipedia.org/wiki/Kalakuta_Republic',
  },
  {
    id: 'm-009',
    category: 'music',
    difficulty: 'medium',
    question: 'Which Nigerian-American artist won a Grammy for the song “Water” in 2024?',
    options: ['Ayra Starr', 'Tyla', 'Tems', 'Asake'],
    correctIndex: 2,
    source: 'https://en.wikipedia.org/wiki/Tems',
  },
  {
    id: 'm-010',
    category: 'music',
    difficulty: 'medium',
    question: 'The talking drum, central to Yoruba music, is locally known as…',
    options: ['Bata', 'Dundun', 'Sakara', 'Gangan'],
    correctIndex: 1,
    source: 'https://en.wikipedia.org/wiki/Talking_drum',
  },

  // ── Nollywood & Literature (10) ──────────────────────────────────────
  {
    id: 'n-001',
    category: 'nollywood',
    difficulty: 'easy',
    question: 'The 1992 film widely credited with launching modern Nollywood is…',
    options: ['Living in Bondage', 'Glamour Girls', 'Domitilla', 'Rattlesnake'],
    correctIndex: 0,
    source: 'https://en.wikipedia.org/wiki/Living_in_Bondage',
  },
  {
    id: 'n-002',
    category: 'nollywood',
    difficulty: 'easy',
    question: 'Hausa-language Nigerian cinema, based largely in Kano, is popularly called…',
    options: ['Ghallywood', 'Kannywood', 'Nollywood', 'Bollywood'],
    correctIndex: 1,
    source: 'https://en.wikipedia.org/wiki/Kannywood',
  },
  {
    id: 'n-003',
    category: 'nollywood',
    difficulty: 'medium',
    question: '“The Wedding Party” (2016) was directed by which Nigerian filmmaker?',
    options: ['Kunle Afolayan', 'Kemi Adetiba', 'Genevieve Nnaji', 'Mo Abudu'],
    correctIndex: 1,
    source: 'https://en.wikipedia.org/wiki/The_Wedding_Party_(2016_film)',
  },
  {
    id: 'n-004',
    category: 'nollywood',
    difficulty: 'medium',
    question: '“Lionheart” (2018), the first Netflix Original from Nigeria, was directed by…',
    options: ['Genevieve Nnaji', 'Mo Abudu', 'Kemi Adetiba', 'Funke Akindele'],
    correctIndex: 0,
    source: 'https://en.wikipedia.org/wiki/Lionheart_(2018_film)',
  },
  {
    id: 'l-001',
    category: 'literature',
    difficulty: 'easy',
    question: 'Who wrote the novel “Things Fall Apart”?',
    options: ['Wole Soyinka', 'Chinua Achebe', 'Ben Okri', 'Cyprian Ekwensi'],
    correctIndex: 1,
    source: 'https://en.wikipedia.org/wiki/Things_Fall_Apart',
  },
  {
    id: 'l-002',
    category: 'literature',
    difficulty: 'medium',
    question: 'Which Nigerian writer became the first African to win the Nobel Prize in Literature?',
    options: ['Wole Soyinka', 'Chinua Achebe', 'Ben Okri', 'Buchi Emecheta'],
    correctIndex: 0,
    source: 'https://en.wikipedia.org/wiki/Wole_Soyinka',
  },
  {
    id: 'l-003',
    category: 'literature',
    difficulty: 'medium',
    question: 'Ben Okri won the Booker Prize in 1991 for which novel?',
    options: ['Flowers and Shadows', 'The Famished Road', 'Dangerous Love', 'Songs of Enchantment'],
    correctIndex: 1,
    source: 'https://en.wikipedia.org/wiki/The_Famished_Road',
  },
  {
    id: 'l-004',
    category: 'literature',
    difficulty: 'easy',
    question: 'Who wrote “Half of a Yellow Sun”?',
    options: ['Chimamanda Ngozi Adichie', 'Buchi Emecheta', 'Sefi Atta', 'Ayobami Adebayo'],
    correctIndex: 0,
    source: 'https://en.wikipedia.org/wiki/Half_of_a_Yellow_Sun',
  },
  {
    id: 'l-005',
    category: 'literature',
    difficulty: 'hard',
    question: 'The novel “The Palm-Wine Drinkard” (1952) was written by…',
    options: ['Amos Tutuola', 'Chinua Achebe', 'D. O. Fagunwa', 'Cyprian Ekwensi'],
    correctIndex: 0,
    source: 'https://en.wikipedia.org/wiki/The_Palm-Wine_Drinkard',
  },
  {
    id: 'n-005',
    category: 'nollywood',
    difficulty: 'medium',
    question: 'Which actress wrote, produced, and starred in the 2020 hit comedy “Omo Ghetto: The Saga”?',
    options: ['Funke Akindele', 'Mercy Johnson', 'Genevieve Nnaji', 'Rita Dominic'],
    correctIndex: 0,
    source: 'https://en.wikipedia.org/wiki/Omo_Ghetto:_The_Saga',
  },

  // ── Sports & Food (10) ────────────────────────────────────────────────
  {
    id: 's-001',
    category: 'sports',
    difficulty: 'easy',
    question: 'The Nigerian senior football team is nicknamed the…',
    options: ['Black Stars', 'Super Eagles', 'Indomitable Lions', 'Bafana Bafana'],
    correctIndex: 1,
    source: 'https://en.wikipedia.org/wiki/Nigeria_national_football_team',
  },
  {
    id: 's-002',
    category: 'sports',
    difficulty: 'medium',
    question: 'Nigeria won its first Olympic gold medal in football at which Games?',
    options: ['Barcelona 1992', 'Atlanta 1996', 'Sydney 2000', 'Athens 2004'],
    correctIndex: 1,
    source: 'https://en.wikipedia.org/wiki/Nigeria_at_the_1996_Summer_Olympics',
  },
  {
    id: 's-003',
    category: 'sports',
    difficulty: 'medium',
    question: 'How many times has Nigeria won the Africa Cup of Nations?',
    options: ['1', '2', '3', '4'],
    correctIndex: 2,
    source: 'https://en.wikipedia.org/wiki/Nigeria_at_the_Africa_Cup_of_Nations',
  },
  {
    id: 's-004',
    category: 'sports',
    difficulty: 'medium',
    question: 'Which Nigerian was named African Footballer of the Year in 1999?',
    options: ['Jay-Jay Okocha', 'Nwankwo Kanu', 'Sunday Oliseh', 'Daniel Amokachi'],
    correctIndex: 1,
    source: 'https://en.wikipedia.org/wiki/Nwankwo_Kanu',
  },
  {
    id: 's-005',
    category: 'sports',
    difficulty: 'hard',
    question: 'Which Nigerian boxer was world heavyweight champion in 1992?',
    options: ['Dick Tiger', 'Hogan Bassey', 'Samuel Peter', 'No Nigerian held that title in 1992'],
    correctIndex: 3,
    source: 'https://en.wikipedia.org/wiki/List_of_world_heavyweight_boxing_champions',
  },
  {
    id: 'f-001',
    category: 'food',
    difficulty: 'easy',
    question: 'What is the main ingredient of Nigerian moi moi?',
    options: ['Maize', 'Beans (cowpeas)', 'Plantain', 'Yam'],
    correctIndex: 1,
    source: 'https://en.wikipedia.org/wiki/Moi_moi',
  },
  {
    id: 'f-002',
    category: 'food',
    difficulty: 'easy',
    question: 'Suya is traditionally made by grilling spiced…',
    options: ['Fish', 'Beef', 'Chicken', 'Goat liver only'],
    correctIndex: 1,
    source: 'https://en.wikipedia.org/wiki/Suya',
  },
  {
    id: 'f-003',
    category: 'food',
    difficulty: 'easy',
    question: 'Garri is processed from which root crop?',
    options: ['Yam', 'Cocoyam', 'Cassava', 'Sweet potato'],
    correctIndex: 2,
    source: 'https://en.wikipedia.org/wiki/Garri',
  },
  {
    id: 'f-004',
    category: 'food',
    difficulty: 'medium',
    question: 'Which leaf is essential to authentic Edikang Ikong soup?',
    options: ['Bitterleaf', 'Ugu (fluted pumpkin)', 'Scent leaf', 'Uziza'],
    correctIndex: 1,
    source: 'https://en.wikipedia.org/wiki/Edikang_Ikong_soup',
  },
  {
    id: 'f-005',
    category: 'food',
    difficulty: 'medium',
    question: 'The “party jollof” trademark smoky flavour comes from…',
    options: ['Adding extra tomatoes', 'Cooking on firewood / open flame', 'Using basmati rice', 'Adding curry powder'],
    correctIndex: 1,
    source: 'https://en.wikipedia.org/wiki/Jollof_rice',
  },
  // ══════════════════════════════════════════════════════════════════════
  // M3 EXPANSION — verified against Wikipedia (evergreen facts only).
  // ══════════════════════════════════════════════════════════════════════

  // ── History (+15) ─────────────────────────────────────────────────────
  {
    id: 'h-011',
    category: 'history',
    difficulty: 'easy',
    question: 'In what year did the Nigerian Civil War (Biafran War) end?',
    options: ['1967', '1970', '1972', '1975'],
    correctIndex: 1,
    source: 'https://en.wikipedia.org/wiki/Nigerian_Civil_War',
  },
  {
    id: 'h-012',
    category: 'history',
    difficulty: 'medium',
    question: 'Who led the breakaway Republic of Biafra?',
    options: ['Yakubu Gowon', 'Odumegwu Ojukwu', 'Murtala Mohammed', 'Olusegun Obasanjo'],
    correctIndex: 1,
    source: 'https://en.wikipedia.org/wiki/Chukwuemeka_Odumegwu_Ojukwu',
  },
  {
    id: 'h-013',
    category: 'history',
    difficulty: 'medium',
    question: 'Which Nigerian Head of State was assassinated in February 1976?',
    options: ['Murtala Mohammed', 'Tafawa Balewa', 'Sani Abacha', 'Aguiyi-Ironsi'],
    correctIndex: 0,
    source: 'https://en.wikipedia.org/wiki/Murtala_Muhammed',
  },
  {
    id: 'h-014',
    category: 'history',
    difficulty: 'easy',
    question: 'In what year did Nigeria become a republic, severing ties with the British monarchy?',
    options: ['1960', '1963', '1966', '1979'],
    correctIndex: 1,
    source: 'https://en.wikipedia.org/wiki/History_of_Nigeria',
  },
  {
    id: 'h-015',
    category: 'history',
    difficulty: 'medium',
    question: 'Who became the first executive President of Nigeria in 1979?',
    options: ['Shehu Shagari', 'Olusegun Obasanjo', 'Nnamdi Azikiwe', 'Muhammadu Buhari'],
    correctIndex: 0,
    source: 'https://en.wikipedia.org/wiki/Shehu_Shagari',
  },
  {
    id: 'h-016',
    category: 'history',
    difficulty: 'medium',
    question: 'The amalgamation of the Northern and Southern Protectorates by Lord Lugard happened in…',
    options: ['1900', '1906', '1914', '1922'],
    correctIndex: 2,
    source: 'https://en.wikipedia.org/wiki/Amalgamation_of_Nigeria',
  },
  {
    id: 'h-017',
    category: 'history',
    difficulty: 'hard',
    question: 'Which queen led a famous 16th-century campaign expanding Zazzau (Zaria)?',
    options: ['Idia', 'Amina', 'Moremi', 'Kambasa'],
    correctIndex: 1,
    source: 'https://en.wikipedia.org/wiki/Amina',
  },
  {
    id: 'h-018',
    category: 'history',
    difficulty: 'medium',
    question: 'The Sokoto Caliphate was founded around 1804 by which leader?',
    options: ['Usman dan Fodio', 'Muhammadu Bello', 'Mansa Musa', 'Askia Muhammad'],
    correctIndex: 0,
    source: 'https://en.wikipedia.org/wiki/Sokoto_Caliphate',
  },
  {
    id: 'h-019',
    category: 'history',
    difficulty: 'easy',
    question: 'Which year is widely cited as the start of the Fourth Republic in Nigeria?',
    options: ['1993', '1999', '2003', '2007'],
    correctIndex: 1,
    source: 'https://en.wikipedia.org/wiki/Fourth_Nigerian_Republic',
  },
  {
    id: 'h-020',
    category: 'history',
    difficulty: 'medium',
    question: 'Who won the annulled June 12, 1993 presidential election?',
    options: ['MKO Abiola', 'Bashir Tofa', 'Olu Falae', 'Ernest Shonekan'],
    correctIndex: 0,
    source: 'https://en.wikipedia.org/wiki/1993_Nigerian_presidential_election',
  },
  {
    id: 'h-021',
    category: 'history',
    difficulty: 'medium',
    question: 'Which kingdom was famous for its bronze plaques looted by the British in 1897?',
    options: ['Oyo Empire', 'Benin Kingdom', 'Nri Kingdom', 'Kanem-Bornu'],
    correctIndex: 1,
    source: 'https://en.wikipedia.org/wiki/Benin_Bronzes',
  },
  {
    id: 'h-022',
    category: 'history',
    difficulty: 'hard',
    question: 'The Aba Women’s Riots (Women’s War) took place in what year?',
    options: ['1914', '1929', '1945', '1953'],
    correctIndex: 1,
    source: 'https://en.wikipedia.org/wiki/Women%27s_War',
  },
  {
    id: 'h-023',
    category: 'history',
    difficulty: 'easy',
    question: 'Who was the British Governor-General that named "Nigeria"?',
    options: ['Frederick Lugard', 'Hugh Clifford', 'Flora Shaw', 'Ralph Moor'],
    correctIndex: 2,
    source: 'https://en.wikipedia.org/wiki/Flora_Shaw,_Lady_Lugard',
  },
  {
    id: 'h-024',
    category: 'history',
    difficulty: 'medium',
    question: 'Which Nigerian leader handed over power to a civilian government in 1979?',
    options: ['Yakubu Gowon', 'Murtala Mohammed', 'Olusegun Obasanjo', 'Ibrahim Babangida'],
    correctIndex: 2,
    source: 'https://en.wikipedia.org/wiki/Olusegun_Obasanjo',
  },
  {
    id: 'h-025',
    category: 'history',
    difficulty: 'medium',
    question: 'General Sani Abacha ruled Nigeria as Head of State from 1993 until his death in…',
    options: ['1996', '1998', '1999', '2000'],
    correctIndex: 1,
    source: 'https://en.wikipedia.org/wiki/Sani_Abacha',
  },

  // ── Geography (+15) ───────────────────────────────────────────────────
  {
    id: 'g-011',
    category: 'geography',
    difficulty: 'easy',
    question: 'How many states does Nigeria have (excluding the FCT)?',
    options: ['30', '34', '36', '37'],
    correctIndex: 2,
    source: 'https://en.wikipedia.org/wiki/States_of_Nigeria',
  },
  {
    id: 'g-012',
    category: 'geography',
    difficulty: 'easy',
    question: 'Which river is the longest in Nigeria?',
    options: ['River Benue', 'River Niger', 'River Kaduna', 'Cross River'],
    correctIndex: 1,
    source: 'https://en.wikipedia.org/wiki/Niger_River',
  },
  {
    id: 'g-013',
    category: 'geography',
    difficulty: 'medium',
    question: 'The Niger and Benue rivers meet ("the Confluence") at which city?',
    options: ['Onitsha', 'Lokoja', 'Makurdi', 'Yola'],
    correctIndex: 1,
    source: 'https://en.wikipedia.org/wiki/Lokoja',
  },
  {
    id: 'g-014',
    category: 'geography',
    difficulty: 'easy',
    question: 'Which country is NOT a land neighbour of Nigeria?',
    options: ['Niger', 'Chad', 'Ghana', 'Cameroon'],
    correctIndex: 2,
    source: 'https://en.wikipedia.org/wiki/Geography_of_Nigeria',
  },
  {
    id: 'g-015',
    category: 'geography',
    difficulty: 'medium',
    question: 'Chappal Waddi, Nigeria’s highest peak, is located in which state?',
    options: ['Plateau', 'Taraba', 'Adamawa', 'Cross River'],
    correctIndex: 1,
    source: 'https://en.wikipedia.org/wiki/Chappal_Waddi',
  },
  {
    id: 'g-016',
    category: 'geography',
    difficulty: 'easy',
    question: 'Which state is known as the "Centre of Excellence"?',
    options: ['Rivers', 'Lagos', 'Kano', 'Oyo'],
    correctIndex: 1,
    source: 'https://en.wikipedia.org/wiki/Lagos_State',
  },
  {
    id: 'g-017',
    category: 'geography',
    difficulty: 'medium',
    question: 'Yankari National Park is located in which state?',
    options: ['Bauchi', 'Plateau', 'Gombe', 'Adamawa'],
    correctIndex: 0,
    source: 'https://en.wikipedia.org/wiki/Yankari_National_Park',
  },
  {
    id: 'g-018',
    category: 'geography',
    difficulty: 'easy',
    question: 'Aso Rock is found in which Nigerian city?',
    options: ['Lagos', 'Kaduna', 'Abuja', 'Jos'],
    correctIndex: 2,
    source: 'https://en.wikipedia.org/wiki/Aso_Rock',
  },
  {
    id: 'g-019',
    category: 'geography',
    difficulty: 'medium',
    question: 'Which state hosts the Olumo Rock?',
    options: ['Ogun', 'Osun', 'Oyo', 'Ondo'],
    correctIndex: 0,
    source: 'https://en.wikipedia.org/wiki/Olumo_Rock',
  },
  {
    id: 'g-020',
    category: 'geography',
    difficulty: 'medium',
    question: 'The Mambilla Plateau is located primarily in which state?',
    options: ['Plateau', 'Taraba', 'Bauchi', 'Benue'],
    correctIndex: 1,
    source: 'https://en.wikipedia.org/wiki/Mambilla_Plateau',
  },
  {
    id: 'g-021',
    category: 'geography',
    difficulty: 'medium',
    question: 'Which Nigerian city is known as "The Tin City"?',
    options: ['Kaduna', 'Jos', 'Enugu', 'Maiduguri'],
    correctIndex: 1,
    source: 'https://en.wikipedia.org/wiki/Jos',
  },
  {
    id: 'g-022',
    category: 'geography',
    difficulty: 'easy',
    question: 'The Atlantic Ocean borders Nigeria along which gulf?',
    options: ['Gulf of Aden', 'Gulf of Guinea', 'Gulf of Sidra', 'Gulf of Oman'],
    correctIndex: 1,
    source: 'https://en.wikipedia.org/wiki/Gulf_of_Guinea',
  },
  {
    id: 'g-023',
    category: 'geography',
    difficulty: 'medium',
    question: 'Which is the largest lake (mostly bordering NE Nigeria) in the region?',
    options: ['Lake Volta', 'Lake Chad', 'Lake Kainji', 'Lake Victoria'],
    correctIndex: 1,
    source: 'https://en.wikipedia.org/wiki/Lake_Chad',
  },
  {
    id: 'g-024',
    category: 'geography',
    difficulty: 'medium',
    question: 'Kainji Dam, built on the River Niger, is in which state?',
    options: ['Kebbi', 'Niger', 'Kwara', 'Sokoto'],
    correctIndex: 1,
    source: 'https://en.wikipedia.org/wiki/Kainji_Dam',
  },
  {
    id: 'g-025',
    category: 'geography',
    difficulty: 'easy',
    question: 'Which state is known as "The Pacesetter State"?',
    options: ['Oyo', 'Osun', 'Ogun', 'Ondo'],
    correctIndex: 0,
    source: 'https://en.wikipedia.org/wiki/Oyo_State',
  },

  // ── Culture (+13) ─────────────────────────────────────────────────────
  {
    id: 'c-008',
    category: 'culture',
    difficulty: 'easy',
    question: 'The Eyo Festival is associated with which city?',
    options: ['Ibadan', 'Lagos', 'Benin City', 'Calabar'],
    correctIndex: 1,
    source: 'https://en.wikipedia.org/wiki/Eyo_festival',
  },
  {
    id: 'c-009',
    category: 'culture',
    difficulty: 'easy',
    question: 'The Argungu Fishing Festival takes place in which state?',
    options: ['Sokoto', 'Kebbi', 'Zamfara', 'Niger'],
    correctIndex: 1,
    source: 'https://en.wikipedia.org/wiki/Argungu_Fishing_Festival',
  },
  {
    id: 'c-010',
    category: 'culture',
    difficulty: 'medium',
    question: 'The Durbar festival is most famously celebrated in which Nigerian city?',
    options: ['Kano', 'Ibadan', 'Enugu', 'Port Harcourt'],
    correctIndex: 0,
    source: 'https://en.wikipedia.org/wiki/Durbar_festival',
  },
  {
    id: 'c-011',
    category: 'culture',
    difficulty: 'easy',
    question: 'The Calabar Carnival is held annually in which state?',
    options: ['Akwa Ibom', 'Cross River', 'Rivers', 'Bayelsa'],
    correctIndex: 1,
    source: 'https://en.wikipedia.org/wiki/Calabar_Carnival',
  },
  {
    id: 'c-012',
    category: 'culture',
    difficulty: 'medium',
    question: 'Which traditional ruler holds the title "Ooni"?',
    options: ['King of Benin', 'Emir of Kano', 'Ruler of Ile-Ife', 'Obi of Onitsha'],
    correctIndex: 2,
    source: 'https://en.wikipedia.org/wiki/Ooni_of_Ife',
  },
  {
    id: 'c-013',
    category: 'culture',
    difficulty: 'medium',
    question: 'The Oba is the traditional ruler of which kingdom?',
    options: ['Benin', 'Oyo', 'Nupe', 'Igala'],
    correctIndex: 0,
    source: 'https://en.wikipedia.org/wiki/Oba_of_Benin',
  },
  {
    id: 'c-014',
    category: 'culture',
    difficulty: 'easy',
    question: 'Aso Oke is a traditional fabric of which ethnic group?',
    options: ['Igbo', 'Yoruba', 'Hausa', 'Tiv'],
    correctIndex: 1,
    source: 'https://en.wikipedia.org/wiki/Aso_oke_hat',
  },
  {
    id: 'c-015',
    category: 'culture',
    difficulty: 'medium',
    question: 'Adire textile is most associated with which Yoruba city?',
    options: ['Ibadan', 'Abeokuta', 'Ile-Ife', 'Ogbomoso'],
    correctIndex: 1,
    source: 'https://en.wikipedia.org/wiki/Adire_(textile_art)',
  },
  {
    id: 'c-016',
    category: 'culture',
    difficulty: 'medium',
    question: 'The Osun-Osogbo Sacred Grove is a UNESCO site. In which state is it?',
    options: ['Oyo', 'Osun', 'Ogun', 'Ekiti'],
    correctIndex: 1,
    source: 'https://en.wikipedia.org/wiki/Osun-Osogbo_Sacred_Grove',
  },
  {
    id: 'c-017',
    category: 'culture',
    difficulty: 'medium',
    question: 'The New Yam Festival ("Iri Ji") is celebrated mainly by which group?',
    options: ['Yoruba', 'Hausa-Fulani', 'Igbo', 'Ijaw'],
    correctIndex: 2,
    source: 'https://en.wikipedia.org/wiki/Iwa_ji',
  },
  {
    id: 'c-018',
    category: 'culture',
    difficulty: 'hard',
    question: 'The Sungbo’s Eredo earthwork is found in which state?',
    options: ['Lagos', 'Ogun', 'Oyo', 'Ondo'],
    correctIndex: 1,
    source: 'https://en.wikipedia.org/wiki/Sungbo%27s_Eredo',
  },
  {
    id: 'c-019',
    category: 'culture',
    difficulty: 'medium',
    question: 'Nok terracotta sculptures originated in which present-day region of Nigeria?',
    options: ['South-East', 'Middle Belt (Kaduna/Plateau)', 'South-West', 'Far North'],
    correctIndex: 1,
    source: 'https://en.wikipedia.org/wiki/Nok_culture',
  },
  {
    id: 'c-020',
    category: 'culture',
    difficulty: 'easy',
    question: 'Which is the traditional Igbo greeting?',
    options: ['Sannu', 'Bawo ni', 'Kedu', 'Mesiere'],
    correctIndex: 2,
    source: 'https://en.wikipedia.org/wiki/Igbo_language',
  },

  // ── Music (+15) ───────────────────────────────────────────────────────
  {
    id: 'm-011',
    category: 'music',
    difficulty: 'easy',
    question: 'Fela Kuti is regarded as the pioneer of which genre?',
    options: ['Highlife', 'Afrobeat', 'Juju', 'Fuji'],
    correctIndex: 1,
    source: 'https://en.wikipedia.org/wiki/Fela_Kuti',
  },
  {
    id: 'm-012',
    category: 'music',
    difficulty: 'easy',
    question: 'King Sunny Ade is a legend of which genre?',
    options: ['Fuji', 'Apala', 'Juju', 'Afrobeat'],
    correctIndex: 2,
    source: 'https://en.wikipedia.org/wiki/King_Sunny_Ad%C3%A9',
  },
  {
    id: 'm-013',
    category: 'music',
    difficulty: 'medium',
    question: 'Sikiru Ayinde Barrister is credited with popularising which genre?',
    options: ['Apala', 'Fuji', 'Sakara', 'Were'],
    correctIndex: 1,
    source: 'https://en.wikipedia.org/wiki/Sikiru_Ayinde_Barrister',
  },
  {
    id: 'm-014',
    category: 'music',
    difficulty: 'medium',
    question: 'Which legendary highlife musician sang "Sweet Mother"?',
    options: ['Victor Olaiya', 'Prince Nico Mbarga', 'Osita Osadebe', 'Rex Lawson'],
    correctIndex: 1,
    source: 'https://en.wikipedia.org/wiki/Sweet_Mother',
  },
  {
    id: 'm-015',
    category: 'music',
    difficulty: 'medium',
    question: 'Wizkid’s breakout debut album was titled…',
    options: ['Ayo', 'Superstar', 'Sounds From The Other Side', 'Made in Lagos'],
    correctIndex: 1,
    source: 'https://en.wikipedia.org/wiki/Superstar_(Wizkid_album)',
  },
  {
    id: 'm-016',
    category: 'music',
    difficulty: 'medium',
    question: 'Davido’s debut studio album is called…',
    options: ['Omo Baba Olowo', 'A Good Time', 'A Better Time', 'Timeless'],
    correctIndex: 0,
    source: 'https://en.wikipedia.org/wiki/Omo_Baba_Olowo',
  },
  {
    id: 'm-017',
    category: 'music',
    difficulty: 'medium',
    question: 'Burna Boy’s Grammy-winning album was…',
    options: ['African Giant', 'Twice as Tall', 'Love, Damini', 'Outside'],
    correctIndex: 1,
    source: 'https://en.wikipedia.org/wiki/Twice_as_Tall',
  },
  {
    id: 'm-018',
    category: 'music',
    difficulty: 'easy',
    question: 'Asa is a singer known for blending soul with…',
    options: ['Fuji', 'Folk / Yoruba sensibilities', 'Apala', 'Gospel only'],
    correctIndex: 1,
    source: 'https://en.wikipedia.org/wiki/Asa_(singer)',
  },
  {
    id: 'm-019',
    category: 'music',
    difficulty: 'medium',
    question: 'The hit "African Queen" was performed by…',
    options: ['D’banj', '2Baba (2Face Idibia)', 'P-Square', 'Faze'],
    correctIndex: 1,
    source: 'https://en.wikipedia.org/wiki/African_Queen_(2Face_Idibia_song)',
  },
  {
    id: 'm-020',
    category: 'music',
    difficulty: 'medium',
    question: 'D’banj’s smash international single was…',
    options: ['Tongolo', 'Oliver Twist', 'Fall in Love', 'Why Me'],
    correctIndex: 1,
    source: 'https://en.wikipedia.org/wiki/Oliver_Twist_(D%27banj_song)',
  },
  {
    id: 'm-021',
    category: 'music',
    difficulty: 'easy',
    question: 'P-Square is a duo made up of brothers Peter and…',
    options: ['Jude', 'Paul', 'Patrick', 'Philip'],
    correctIndex: 1,
    source: 'https://en.wikipedia.org/wiki/P-Square',
  },
  {
    id: 'm-022',
    category: 'music',
    difficulty: 'medium',
    question: 'Femi Kuti and Seun Kuti are sons of which legend?',
    options: ['Victor Uwaifo', 'Fela Kuti', 'Sonny Okosun', 'Onyeka Onwenu'],
    correctIndex: 1,
    source: 'https://en.wikipedia.org/wiki/Fela_Kuti',
  },
  {
    id: 'm-023',
    category: 'music',
    difficulty: 'medium',
    question: '"Joromi" is a classic Nigerian song by…',
    options: ['Sir Victor Uwaifo', 'Bobby Benson', 'Ebenezer Obey', 'Haruna Ishola'],
    correctIndex: 0,
    source: 'https://en.wikipedia.org/wiki/Victor_Uwaifo',
  },
  {
    id: 'm-024',
    category: 'music',
    difficulty: 'easy',
    question: 'Tiwa Savage is signed to which iconic label launched by Don Jazzy?',
    options: ['Mavin Records', 'Chocolate City', 'YBNL', 'DMW'],
    correctIndex: 0,
    source: 'https://en.wikipedia.org/wiki/Mavin_Records',
  },
  {
    id: 'm-025',
    category: 'music',
    difficulty: 'medium',
    question: 'Olamide founded which record label?',
    options: ['DMW', 'Mavin', 'YBNL Nation', 'Starboy'],
    correctIndex: 2,
    source: 'https://en.wikipedia.org/wiki/Olamide',
  },

  // ── Nollywood (+15) ───────────────────────────────────────────────────
  {
    id: 'n-006',
    category: 'nollywood',
    difficulty: 'medium',
    question: 'Genevieve Nnaji directed which acclaimed film acquired by Netflix?',
    options: ['Lionheart', 'King of Boys', '93 Days', 'The Wedding Party'],
    correctIndex: 0,
    source: 'https://en.wikipedia.org/wiki/Lionheart_(2018_film)',
  },
  {
    id: 'n-007',
    category: 'nollywood',
    difficulty: 'easy',
    question: 'Who directed "The Wedding Party" (2016)?',
    options: ['Kemi Adetiba', 'Mo Abudu', 'Kunle Afolayan', 'Genevieve Nnaji'],
    correctIndex: 0,
    source: 'https://en.wikipedia.org/wiki/The_Wedding_Party_(2016_film)',
  },
  {
    id: 'n-008',
    category: 'nollywood',
    difficulty: 'medium',
    question: 'Kemi Adetiba’s 2018 political thriller is titled…',
    options: ['King of Boys', 'Chief Daddy', 'Merry Men', 'The CEO'],
    correctIndex: 0,
    source: 'https://en.wikipedia.org/wiki/King_of_Boys',
  },
  {
    id: 'n-009',
    category: 'nollywood',
    difficulty: 'medium',
    question: 'Which film by Kunle Afolayan dramatises the 1976 coup?',
    options: ['Figurine', 'October 1', 'Phone Swap', 'Mokalik'],
    correctIndex: 1,
    source: 'https://en.wikipedia.org/wiki/October_1_(film)',
  },
  {
    id: 'n-010',
    category: 'nollywood',
    difficulty: 'medium',
    question: '"93 Days" dramatised which Nigerian public-health story?',
    options: ['Lassa fever outbreak', 'Ebola containment in Lagos', 'COVID-19 response', 'Polio eradication'],
    correctIndex: 1,
    source: 'https://en.wikipedia.org/wiki/93_Days',
  },
  {
    id: 'n-011',
    category: 'nollywood',
    difficulty: 'easy',
    question: 'Pete Edochie became iconic playing which Achebe character?',
    options: ['Ezeulu', 'Okonkwo', 'Obi Okonkwo', 'Unoka'],
    correctIndex: 1,
    source: 'https://en.wikipedia.org/wiki/Pete_Edochie',
  },
  {
    id: 'n-012',
    category: 'nollywood',
    difficulty: 'medium',
    question: 'The 1992 film widely credited with sparking modern Nollywood is…',
    options: ['Living in Bondage', 'Glamour Girls', 'Domitilla', 'Nneka the Pretty Serpent'],
    correctIndex: 0,
    source: 'https://en.wikipedia.org/wiki/Living_in_Bondage',
  },
  {
    id: 'n-013',
    category: 'nollywood',
    difficulty: 'medium',
    question: 'Tunde Kelani is renowned as a director, particularly in which language tradition?',
    options: ['Igbo', 'Yoruba', 'Hausa', 'Pidgin only'],
    correctIndex: 1,
    source: 'https://en.wikipedia.org/wiki/Tunde_Kelani',
  },
  {
    id: 'n-014',
    category: 'nollywood',
    difficulty: 'easy',
    question: 'Mo Abudu founded which media company behind major Nollywood productions?',
    options: ['EbonyLife', 'Inkblot', 'FilmOne', 'Anakle'],
    correctIndex: 0,
    source: 'https://en.wikipedia.org/wiki/Mo_Abudu',
  },
  {
    id: 'n-015',
    category: 'nollywood',
    difficulty: 'medium',
    question: 'Rita Dominic starred in which AMAA-winning historical drama (2022)?',
    options: ['The Milkmaid', 'La Femme Anjola', 'The Perfect Arrangement', 'The Resort'],
    correctIndex: 0,
    source: 'https://en.wikipedia.org/wiki/Rita_Dominic',
  },
  {
    id: 'n-016',
    category: 'nollywood',
    difficulty: 'medium',
    question: 'Which Niyi Akinmolayan film was once Nollywood’s highest-grossing?',
    options: ['Prophetess', 'The Set Up', 'Chief Daddy 2', 'A Naija Christmas'],
    correctIndex: 2,
    source: 'https://en.wikipedia.org/wiki/Niyi_Akinmolayan',
  },
  {
    id: 'n-017',
    category: 'nollywood',
    difficulty: 'medium',
    question: 'Funke Akindele is best known for which long-running comedy series?',
    options: ['Jenifa’s Diary', 'Tinsel', 'Skinny Girl in Transit', 'Hush'],
    correctIndex: 0,
    source: 'https://en.wikipedia.org/wiki/Jenifa%27s_Diary',
  },
  {
    id: 'n-018',
    category: 'nollywood',
    difficulty: 'easy',
    question: 'Who is famously nicknamed the "Asaba" of comedy in Nigerian cinema… actually played the role of Patience in many films?',
    options: ['Patience Ozokwor', 'Chioma Akpotha', 'Mercy Johnson', 'Ngozi Ezeonu'],
    correctIndex: 0,
    source: 'https://en.wikipedia.org/wiki/Patience_Ozokwor',
  },
  {
    id: 'n-019',
    category: 'nollywood',
    difficulty: 'medium',
    question: 'Ramsey Nouah’s 2020 directorial debut was a sequel to which classic?',
    options: ['Glamour Girls', 'Living in Bondage', 'Nneka the Pretty Serpent', 'Domitilla'],
    correctIndex: 1,
    source: 'https://en.wikipedia.org/wiki/Living_in_Bondage:_Breaking_Free',
  },
  {
    id: 'n-020',
    category: 'nollywood',
    difficulty: 'medium',
    question: '"Anikulapo" (2022), set in old Oyo, was directed by…',
    options: ['Kunle Afolayan', 'Tunde Kelani', 'Niyi Akinmolayan', 'Biyi Bandele'],
    correctIndex: 0,
    source: 'https://en.wikipedia.org/wiki/Anikulapo',
  },

  // ── Sports (+15) ──────────────────────────────────────────────────────
  {
    id: 's-006',
    category: 'sports',
    difficulty: 'easy',
    question: 'The Super Eagles won their first AFCON title in which year?',
    options: ['1980', '1984', '1990', '1994'],
    correctIndex: 0,
    source: 'https://en.wikipedia.org/wiki/Nigeria_national_football_team',
  },
  {
    id: 's-007',
    category: 'sports',
    difficulty: 'medium',
    question: 'Nigeria has won the Africa Cup of Nations how many times?',
    options: ['Two', 'Three', 'Four', 'Five'],
    correctIndex: 1,
    source: 'https://en.wikipedia.org/wiki/Nigeria_national_football_team',
  },
  {
    id: 's-008',
    category: 'sports',
    difficulty: 'easy',
    question: 'At which Olympics did Nigeria’s U-23 football team win gold?',
    options: ['Atlanta 1996', 'Sydney 2000', 'Beijing 2008', 'London 2012'],
    correctIndex: 0,
    source: 'https://en.wikipedia.org/wiki/Football_at_the_1996_Summer_Olympics',
  },
  {
    id: 's-009',
    category: 'sports',
    difficulty: 'medium',
    question: 'Who scored the golden goal that beat Argentina in the Atlanta ’96 final?',
    options: ['Nwankwo Kanu', 'Daniel Amokachi', 'Emmanuel Amunike', 'Jay-Jay Okocha'],
    correctIndex: 2,
    source: 'https://en.wikipedia.org/wiki/Emmanuel_Amunike',
  },
  {
    id: 's-010',
    category: 'sports',
    difficulty: 'medium',
    question: 'Rashidi Yekini scored Nigeria’s first ever World Cup goal at which tournament?',
    options: ['1994 USA', '1998 France', '2002 Korea/Japan', '2010 South Africa'],
    correctIndex: 0,
    source: 'https://en.wikipedia.org/wiki/Rashidi_Yekini',
  },
  {
    id: 's-011',
    category: 'sports',
    difficulty: 'easy',
    question: 'Jay-Jay Okocha played for which English Premier League club?',
    options: ['Bolton Wanderers', 'Tottenham', 'Everton', 'West Ham'],
    correctIndex: 0,
    source: 'https://en.wikipedia.org/wiki/Jay-Jay_Okocha',
  },
  {
    id: 's-012',
    category: 'sports',
    difficulty: 'medium',
    question: 'Nwankwo Kanu won the Champions League with which club?',
    options: ['Arsenal', 'Ajax', 'Inter Milan', 'Portsmouth'],
    correctIndex: 1,
    source: 'https://en.wikipedia.org/wiki/Nwankwo_Kanu',
  },
  {
    id: 's-013',
    category: 'sports',
    difficulty: 'medium',
    question: 'Which Nigerian was named African Footballer of the Year in 1999?',
    options: ['Sunday Oliseh', 'Nwankwo Kanu', 'Jay-Jay Okocha', 'Finidi George'],
    correctIndex: 1,
    source: 'https://en.wikipedia.org/wiki/Nwankwo_Kanu',
  },
  {
    id: 's-014',
    category: 'sports',
    difficulty: 'medium',
    question: 'Mary Onyali is a Nigerian legend in which sport?',
    options: ['Long jump', 'Sprinting (track)', 'Boxing', 'Basketball'],
    correctIndex: 1,
    source: 'https://en.wikipedia.org/wiki/Mary_Onyali',
  },
  {
    id: 's-015',
    category: 'sports',
    difficulty: 'medium',
    question: 'Chioma Ajunwa won Nigeria’s first individual Olympic gold in which event?',
    options: ['100m sprint', 'Long jump', '400m hurdles', 'Triple jump'],
    correctIndex: 1,
    source: 'https://en.wikipedia.org/wiki/Chioma_Ajunwa',
  },
  {
    id: 's-016',
    category: 'sports',
    difficulty: 'medium',
    question: 'Hakeem Olajuwon won NBA championships with which franchise?',
    options: ['Lakers', 'Rockets', 'Bulls', 'Spurs'],
    correctIndex: 1,
    source: 'https://en.wikipedia.org/wiki/Hakeem_Olajuwon',
  },
  {
    id: 's-017',
    category: 'sports',
    difficulty: 'medium',
    question: 'Anthony Joshua holds Nigerian heritage and competes in which sport?',
    options: ['MMA', 'Boxing', 'Wrestling', 'Kickboxing'],
    correctIndex: 1,
    source: 'https://en.wikipedia.org/wiki/Anthony_Joshua',
  },
  {
    id: 's-018',
    category: 'sports',
    difficulty: 'easy',
    question: 'The D’Tigers represent Nigeria in which sport?',
    options: ['Volleyball', 'Basketball', 'Handball', 'Hockey'],
    correctIndex: 1,
    source: 'https://en.wikipedia.org/wiki/Nigeria_national_basketball_team',
  },
  {
    id: 's-019',
    category: 'sports',
    difficulty: 'medium',
    question: 'Nigeria’s women’s football team is nicknamed the…',
    options: ['Super Falcons', 'Golden Eaglets', 'Flying Eagles', 'Super Eagles'],
    correctIndex: 0,
    source: 'https://en.wikipedia.org/wiki/Nigeria_women%27s_national_football_team',
  },
  {
    id: 's-020',
    category: 'sports',
    difficulty: 'medium',
    question: 'Nigeria’s U-17 team is nicknamed the…',
    options: ['Flying Eagles', 'Golden Eaglets', 'Super Eagles', 'Junior Falcons'],
    correctIndex: 1,
    source: 'https://en.wikipedia.org/wiki/Nigeria_national_under-17_football_team',
  },

  // ── Food (+10) ────────────────────────────────────────────────────────
  {
    id: 'f-006',
    category: 'food',
    difficulty: 'easy',
    question: 'Suya is traditionally seasoned with which spice mix?',
    options: ['Curry', 'Yaji', 'Garam masala', 'Berbere'],
    correctIndex: 1,
    source: 'https://en.wikipedia.org/wiki/Suya',
  },
  {
    id: 'f-007',
    category: 'food',
    difficulty: 'medium',
    question: 'Tuwo Shinkafa is made from which staple?',
    options: ['Maize', 'Rice', 'Sorghum', 'Cassava'],
    correctIndex: 1,
    source: 'https://en.wikipedia.org/wiki/Tuwo_shinkafa',
  },
  {
    id: 'f-008',
    category: 'food',
    difficulty: 'easy',
    question: 'Akara is made primarily from…',
    options: ['Black-eyed peas', 'Plantain', 'Yam', 'Cassava'],
    correctIndex: 0,
    source: 'https://en.wikipedia.org/wiki/Akara',
  },
  {
    id: 'f-009',
    category: 'food',
    difficulty: 'medium',
    question: 'Moin moin is steamed and made from…',
    options: ['Maize', 'Beans (black-eyed peas)', 'Sorghum', 'Wheat flour'],
    correctIndex: 1,
    source: 'https://en.wikipedia.org/wiki/Moin_moin',
  },
  {
    id: 'f-010',
    category: 'food',
    difficulty: 'medium',
    question: 'Banga soup uses the extract of which fruit?',
    options: ['Coconut', 'Palm fruit', 'Breadfruit', 'Tamarind'],
    correctIndex: 1,
    source: 'https://en.wikipedia.org/wiki/Banga_soup',
  },
  {
    id: 'f-011',
    category: 'food',
    difficulty: 'medium',
    question: 'Nkwobi is a delicacy traditionally made with…',
    options: ['Cow foot', 'Goat head', 'Snail', 'Chicken gizzards'],
    correctIndex: 0,
    source: 'https://en.wikipedia.org/wiki/Nkwobi',
  },
  {
    id: 'f-012',
    category: 'food',
    difficulty: 'easy',
    question: 'Fufu is most commonly made from…',
    options: ['Cassava', 'Yam', 'Maize', 'Plantain'],
    correctIndex: 0,
    source: 'https://en.wikipedia.org/wiki/Fufu',
  },
  {
    id: 'f-013',
    category: 'food',
    difficulty: 'medium',
    question: 'Which soup is famed for its stretchy "draw" from okro/ogbono?',
    options: ['Egusi', 'Ogbono', 'Efo riro', 'Banga'],
    correctIndex: 1,
    source: 'https://en.wikipedia.org/wiki/Ogbono_soup',
  },
  {
    id: 'f-014',
    category: 'food',
    difficulty: 'easy',
    question: 'Egusi soup is thickened with seeds of which plant?',
    options: ['Watermelon', 'Pumpkin / melon (Citrullus)', 'Sesame', 'Pumpkin (Cucurbita)'],
    correctIndex: 1,
    source: 'https://en.wikipedia.org/wiki/Egusi',
  },
  {
    id: 'f-015',
    category: 'food',
    difficulty: 'medium',
    question: 'Kunu is a traditional drink primarily made from…',
    options: ['Hibiscus', 'Millet/sorghum (or tigernut)', 'Ginger root only', 'Cocoa'],
    correctIndex: 1,
    source: 'https://en.wikipedia.org/wiki/Kunu',
  },

  // ── Language (+10) ────────────────────────────────────────────────────
  {
    id: 'l-004',
    category: 'language',
    difficulty: 'easy',
    question: 'How do you say "thank you" in Yoruba?',
    options: ['E se', 'Daalu', 'Na gode', 'Sannu'],
    correctIndex: 0,
    source: 'https://en.wikipedia.org/wiki/Yoruba_language',
  },
  {
    id: 'l-005',
    category: 'language',
    difficulty: 'easy',
    question: '"Daalu" means "thank you" in which language?',
    options: ['Hausa', 'Igbo', 'Yoruba', 'Efik'],
    correctIndex: 1,
    source: 'https://en.wikipedia.org/wiki/Igbo_language',
  },
  {
    id: 'l-006',
    category: 'language',
    difficulty: 'easy',
    question: '"Na gode" means "thank you" in which language?',
    options: ['Hausa', 'Igbo', 'Yoruba', 'Tiv'],
    correctIndex: 0,
    source: 'https://en.wikipedia.org/wiki/Hausa_language',
  },
  {
    id: 'l-007',
    category: 'language',
    difficulty: 'medium',
    question: 'Which Nigerian language is written in Ajami script as well as Latin?',
    options: ['Igbo', 'Hausa', 'Yoruba', 'Efik'],
    correctIndex: 1,
    source: 'https://en.wikipedia.org/wiki/Hausa_language',
  },
  {
    id: 'l-008',
    category: 'language',
    difficulty: 'medium',
    question: 'Approximately how many languages are spoken across Nigeria?',
    options: ['About 50', 'About 100', 'Over 250', 'Over 500'],
    correctIndex: 3,
    source: 'https://en.wikipedia.org/wiki/Languages_of_Nigeria',
  },
  {
    id: 'l-009',
    category: 'language',
    difficulty: 'medium',
    question: 'Nigerian Pidgin English-based creole has roots dating to which era?',
    options: ['Atlantic slave trade era', '1900s colonial radio', '1960s independence', '1990s telecoms boom'],
    correctIndex: 0,
    source: 'https://en.wikipedia.org/wiki/Nigerian_Pidgin',
  },
  {
    id: 'l-010',
    category: 'language',
    difficulty: 'easy',
    question: 'In Pidgin, "wahala" means…',
    options: ['Money', 'Trouble', 'Friend', 'Food'],
    correctIndex: 1,
    source: 'https://en.wikipedia.org/wiki/Nigerian_Pidgin',
  },
  {
    id: 'l-011',
    category: 'language',
    difficulty: 'easy',
    question: 'In Yoruba, "Bawo ni" means…',
    options: ['Goodbye', 'How are you?', 'Welcome', 'Thank you'],
    correctIndex: 1,
    source: 'https://en.wikipedia.org/wiki/Yoruba_language',
  },
  {
    id: 'l-012',
    category: 'language',
    difficulty: 'medium',
    question: 'Which language family does Igbo belong to?',
    options: ['Afro-Asiatic', 'Niger-Congo', 'Nilo-Saharan', 'Khoisan'],
    correctIndex: 1,
    source: 'https://en.wikipedia.org/wiki/Igbo_language',
  },
  {
    id: 'l-013',
    category: 'language',
    difficulty: 'medium',
    question: 'Hausa is part of which language family?',
    options: ['Niger-Congo', 'Afro-Asiatic (Chadic)', 'Nilo-Saharan', 'Indo-European'],
    correctIndex: 1,
    source: 'https://en.wikipedia.org/wiki/Hausa_language',
  },

  // ── Literature (+10) ──────────────────────────────────────────────────
  {
    id: 'lit-006',
    category: 'literature',
    difficulty: 'easy',
    question: 'Wole Soyinka won the Nobel Prize in Literature in which year?',
    options: ['1976', '1986', '1996', '2006'],
    correctIndex: 1,
    source: 'https://en.wikipedia.org/wiki/Wole_Soyinka',
  },
  {
    id: 'lit-007',
    category: 'literature',
    difficulty: 'easy',
    question: 'Chinua Achebe’s "Things Fall Apart" was first published in…',
    options: ['1948', '1958', '1968', '1978'],
    correctIndex: 1,
    source: 'https://en.wikipedia.org/wiki/Things_Fall_Apart',
  },
  {
    id: 'lit-008',
    category: 'literature',
    difficulty: 'medium',
    question: 'Chimamanda Adichie’s novel about the Biafran War is…',
    options: ['Purple Hibiscus', 'Half of a Yellow Sun', 'Americanah', 'The Thing Around Your Neck'],
    correctIndex: 1,
    source: 'https://en.wikipedia.org/wiki/Half_of_a_Yellow_Sun',
  },
  {
    id: 'lit-009',
    category: 'literature',
    difficulty: 'medium',
    question: '"The Famished Road" won the Booker Prize for which Nigerian author?',
    options: ['Ben Okri', 'Helon Habila', 'Chigozie Obioma', 'Teju Cole'],
    correctIndex: 0,
    source: 'https://en.wikipedia.org/wiki/The_Famished_Road',
  },
  {
    id: 'lit-010',
    category: 'literature',
    difficulty: 'medium',
    question: 'Cyprian Ekwensi is best known for which novel set in Lagos nightlife?',
    options: ['Jagua Nana', 'People of the City', 'Burning Grass', 'The Drummer Boy'],
    correctIndex: 0,
    source: 'https://en.wikipedia.org/wiki/Jagua_Nana',
  },
  {
    id: 'lit-011',
    category: 'literature',
    difficulty: 'medium',
    question: 'Buchi Emecheta’s acclaimed novel about motherhood is…',
    options: ['The Joys of Motherhood', 'Second Class Citizen', 'Kehinde', 'The Bride Price'],
    correctIndex: 0,
    source: 'https://en.wikipedia.org/wiki/The_Joys_of_Motherhood',
  },
  {
    id: 'lit-012',
    category: 'literature',
    difficulty: 'medium',
    question: 'Ken Saro-Wiwa was an author and activist for which people?',
    options: ['Igbo', 'Ogoni', 'Ijaw', 'Yoruba'],
    correctIndex: 1,
    source: 'https://en.wikipedia.org/wiki/Ken_Saro-Wiwa',
  },
  {
    id: 'lit-013',
    category: 'literature',
    difficulty: 'medium',
    question: 'Christopher Okigbo, the celebrated poet, died fighting in which war?',
    options: ['WWII', 'Nigerian Civil War', 'Congo Crisis', 'Algerian War'],
    correctIndex: 1,
    source: 'https://en.wikipedia.org/wiki/Christopher_Okigbo',
  },
  {
    id: 'lit-014',
    category: 'literature',
    difficulty: 'medium',
    question: 'D.O. Fagunwa wrote primarily in which language?',
    options: ['English', 'Yoruba', 'Igbo', 'Hausa'],
    correctIndex: 1,
    source: 'https://en.wikipedia.org/wiki/D._O._Fagunwa',
  },
  {
    id: 'lit-015',
    category: 'literature',
    difficulty: 'medium',
    question: 'Amos Tutuola’s most famous work is…',
    options: ['The Palm-Wine Drinkard', 'My Life in the Bush of Ghosts', 'Simbi and the Satyr of the Dark Jungle', 'Ajaiyi and his Inherited Poverty'],
    correctIndex: 0,
    source: 'https://en.wikipedia.org/wiki/The_Palm-Wine_Drinkard',
  },

  // ── General (+12) ─────────────────────────────────────────────────────
  {
    id: 'gen-001',
    category: 'general',
    difficulty: 'easy',
    question: 'What are the colours of the Nigerian flag?',
    options: ['Green-White-Green', 'Green-Yellow-Green', 'White-Green-White', 'Green-White-Red'],
    correctIndex: 0,
    source: 'https://en.wikipedia.org/wiki/Flag_of_Nigeria',
  },
  {
    id: 'gen-002',
    category: 'general',
    difficulty: 'easy',
    question: 'Nigeria’s national currency is the…',
    options: ['Cedi', 'Naira', 'Shilling', 'Franc'],
    correctIndex: 1,
    source: 'https://en.wikipedia.org/wiki/Nigerian_naira',
  },
  {
    id: 'gen-003',
    category: 'general',
    difficulty: 'easy',
    question: 'Nigeria’s national anthem (reinstated 2024) begins with…',
    options: ['"Arise, O Compatriots"', '"Nigeria We Hail Thee"', '"God Bless Nigeria"', '"O Land of Promise"'],
    correctIndex: 1,
    source: 'https://en.wikipedia.org/wiki/Nigeria,_We_Hail_Thee',
  },
  {
    id: 'gen-004',
    category: 'general',
    difficulty: 'easy',
    question: 'The Nigerian coat of arms features which animals?',
    options: ['Two lions', 'Two horses', 'An eagle and two horses', 'A lion and an eagle'],
    correctIndex: 2,
    source: 'https://en.wikipedia.org/wiki/Coat_of_arms_of_Nigeria',
  },
  {
    id: 'gen-005',
    category: 'general',
    difficulty: 'easy',
    question: 'The capital of Nigeria moved from Lagos to Abuja in which year?',
    options: ['1976', '1986', '1991', '1999'],
    correctIndex: 2,
    source: 'https://en.wikipedia.org/wiki/Abuja',
  },
  {
    id: 'gen-006',
    category: 'general',
    difficulty: 'medium',
    question: 'Nigeria is a member of which oil-producers’ organisation?',
    options: ['OPEC', 'WTO only', 'G7', 'EU'],
    correctIndex: 0,
    source: 'https://en.wikipedia.org/wiki/OPEC',
  },
  {
    id: 'gen-007',
    category: 'general',
    difficulty: 'medium',
    question: 'Nigeria’s telephone country code is…',
    options: ['+233', '+234', '+254', '+27'],
    correctIndex: 1,
    source: 'https://en.wikipedia.org/wiki/Telephone_numbers_in_Nigeria',
  },
  {
    id: 'gen-008',
    category: 'general',
    difficulty: 'medium',
    question: 'The first GSM call in Nigeria was made in which year?',
    options: ['1998', '2001', '2003', '2005'],
    correctIndex: 1,
    source: 'https://en.wikipedia.org/wiki/Telecommunications_in_Nigeria',
  },
  {
    id: 'gen-009',
    category: 'general',
    difficulty: 'easy',
    question: 'The University of Ibadan, Nigeria’s oldest university, was founded in…',
    options: ['1948', '1956', '1962', '1970'],
    correctIndex: 0,
    source: 'https://en.wikipedia.org/wiki/University_of_Ibadan',
  },
  {
    id: 'gen-010',
    category: 'general',
    difficulty: 'medium',
    question: 'Which Nigerian became Director-General of the WTO in 2021?',
    options: ['Ngozi Okonjo-Iweala', 'Amina Mohammed', 'Akinwumi Adesina', 'Obiageli Ezekwesili'],
    correctIndex: 0,
    source: 'https://en.wikipedia.org/wiki/Ngozi_Okonjo-Iweala',
  },
  {
    id: 'gen-011',
    category: 'general',
    difficulty: 'medium',
    question: 'NAFDAC is the Nigerian agency responsible for…',
    options: ['Drugs and food regulation', 'Aviation safety', 'Border control', 'Telecoms regulation'],
    correctIndex: 0,
    source: 'https://en.wikipedia.org/wiki/National_Agency_for_Food_and_Drug_Administration_and_Control',
  },
  {
    id: 'gen-012',
    category: 'general',
    difficulty: 'easy',
    question: 'Nigeria’s Independence Day is celebrated on…',
    options: ['October 1', 'October 12', 'May 29', 'June 12'],
    correctIndex: 0,
    source: 'https://en.wikipedia.org/wiki/Independence_Day_(Nigeria)',
  },
];

/** Lookup by category for round generation. */
export function questionsByCategory(category: TriviaQuestion['category']): TriviaQuestion[] {
  return TRIVIA_BANK.filter((q) => q.category === category);
}

/** All categories that currently have at least one question. */
export function availableCategories(): TriviaQuestion['category'][] {
  return Array.from(new Set(TRIVIA_BANK.map((q) => q.category)));
}
